exclude: ^tests/|^mallow_notifications/sns/schema/
default_stages: [pre-commit, manual] # runs on the staged contents of files by temporarily stashing the unstaged changes while running hooks.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
      name: Check YAML
      description: Simply check YAML files for parseable syntax.
    - id: check-merge-conflict
      name: Check Merge Conflict String
      description: Check for files that contain merge conflict strings.
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
      name: Black Formatter
      description: Format Python code using Black
      entry: black
      language_version: python3.9
  - repo: https://github.com/pycqa/isort 
    rev: 5.12.0 
    hooks: 
    - id: isort 
      name: Isort Formatter
      description: Sort Python imports based on the import locality
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
    - id: docformatter
      name: Docformatter
      description: 'Formats docstrings to follow PEP 257.'
      additional_dependencies: [tomli]
      args: [--in-place, --config, ./pyproject.toml] # Hook configured based config added in pyproject.toml
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.0.3
    hooks:
    - id: pylint
      name: Pylint
      description: Lint Python code
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
    - id: bandit
      name: Bandit 
      description: 'Bandit is a tool for finding common security issues in Python code'
